### ISSUE TITLE
The font of the navigation is blurry

### ISSUE THREAD

**Issue by todortotev** [mgechev/revive.run#16]
![Screenshot 2020-09-16 at 18 17 24](https://user-images.githubusercontent.com/51530311/93357365-e023d580-f848-11ea-8713-3187f3b62e31.png)

**Comment by todortotev** [comment]
@mgechev I can publish a PR to fix it if you are okay with that?

**Comment by mgechev** [comment]
Sounds good, please go ahead. Thank you!
